version: '3'

services:
  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - data-db:/data/db
    restart: always
  backend:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./backend
    env_file:
      - .env
    ports:
      - "8001:8000"
    restart: always
  frontend:
    depends_on:
      - backend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    env_file:
      - .env
    ports:
      - "3000:80"
volumes:
  data-db: